apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  namespace: jmeter
  labels:
    jmeter_mode: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
      - name: jmslave
        image: jesperrasmussen/jmeter-slave
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1099
        - containerPort: 50000
        resources: {}
