apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: brigade
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31500